#!/bin/sh

ln -s ./profile/profile.config ~/.profile
ln -s ./bash/bashrc.config ~/.bashrc
ln -s ./zsh/zshrc.config ~/.zshrc
ln -s ./nvim/init.vim ~/.config/nvim/init.vim
ln -s ./nvim/nvim_config ~/.config/nvim/nvim_config
ln -s ./rofi ~/.config/rofi
ln -s ./neofetch ~/.config/neofetch
ln -s ./ranger ~/.config/ranger
ln -s ./mutt ~/.config/mutt
ln -s ./mpd ~/.config/mpd
