source $HOME/git/dotfiles/vim/vim_config/plugin_config/airline.vim
source $HOME/git/dotfiles/vim/vim_config/plugin_config/ale.vim
source $HOME/git/dotfiles/vim/vim_config/plugin_config/deoplete.vim
source $HOME/git/dotfiles/vim/vim_config/plugin_config/gruvbox.vim
source $HOME/git/dotfiles/vim/vim_config/plugin_config/nerdtree.vim
source $HOME/git/dotfiles/vim/vim_config/plugin_config/pythonsense.vim
source $HOME/git/dotfiles/vim/vim_config/plugin_config/rainbowparentheses.vim
source $HOME/git/dotfiles/vim/vim_config/plugin_config/simplyfold.vim
source $HOME/git/dotfiles/vim/vim_config/plugin_config/slime.vim
source $HOME/git/dotfiles/vim/vim_config/plugin_config/utilsnips.vim
